#!/bin/sh
choice=$(dmenu_path | dmenu "$@")
[ -z "$choice" ] && exit

case "$choice" in
	qutebrowser) exec qutebrowser --basedir ~/.runtime/qutebrowser-yeyito ;;
	*) exec ${SHELL:-"/bin/sh"} -c "$choice" ;;
esac
